# Generated by Django 5.0.3 on 2024-03-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha_kiralama_app', '0002_userprofile_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='username',
        ),
    ]
