# Generated by Django 5.0.3 on 2024-03-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha_kiralama_app', '0003_rename_user_name_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iha',
            name='marka',
        ),
    ]
