# Generated by Django 5.0.3 on 2024-03-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha_kiralama_app', '0006_alter_kiralananiha_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='iha',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='kiralananiha',
            name='iha_id',
        ),
        migrations.RemoveField(
            model_name='kiralananiha',
            name='user_id',
        ),
        migrations.AddField(
            model_name='iha',
            name='marka',
            field=models.CharField(default='foobar', max_length=100),
        ),
        migrations.AddField(
            model_name='iha',
            name='uzunluk',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='kiralananiha',
            name='iha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iha_kiralama_app.iha'),
        ),
        migrations.AddField(
            model_name='kiralananiha',
            name='kiralayan_uye',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kiralamakaydi',
            name='iha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iha_kiralama_app.iha'),
        ),
    ]
