# Generated by Django 5.0.3 on 2024-03-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha_kiralama_app', '0007_delete_userprofile_remove_iha_kategori_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KiralamaKaydi',
        ),
    ]
