# Generated by Django 5.0.3 on 2024-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha_kiralama_app', '0008_delete_kiralamakaydi'),
    ]

    operations = [
        migrations.AddField(
            model_name='iha',
            name='havada_kalıs_suresi',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='iha',
            name='uzunluk',
            field=models.FloatField(),
        ),
    ]
